openapi: 3.0.0
info:
  title: BDV-NOVAK Copy
  description: Inttegrio API Rest Services
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:8585/inttegriorest/service
  variables: {}
- url: http://192.168.10.119:8585/inttegriorest/service
  variables: {}
- url: http://172.31.0.33:30010/inttegriorest/service
  variables: {}
paths:
  /createAccountBdv:
    post:
      tags:
      - BDV NOVAK
      summary: Create Account
      description: 'API diseñado para crear una cuenta dentro de Inttegrio con los siguientes datos enviados desde un sistema externo: Número de cuenta o contrato, sucursal, moneda y la lista de propietarios o participantes en el contrato de la cuenta que figuren tanto como propietarios o como firmantes. En este caso se asume que ambos perfiles pueden movilizar los fondos de la cuenta. En el caso de cuentas para empresas o entidades dicha empresa o entidad debe colocarse como propietario de la cuenta y las personas naturales que movilizan la cuenta se definen como los propietarios de la misma o como sus firmantes.'
      operationId: CreateAccount
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJlMWQ0MzMwNzI4OGM0MWZhODhlY2I2YmE1MjBmOTRjYSIsImlhdCI6MTYwMTAxMDAwMCwibmJmIjoxNTc3ODU0ODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6IkZCRU5JVEVaIiwibWFpbCI6ImZiZW5pdGV6QGludHRlZ3Jpby5jb20iLCJ1c2VyQ3VzdG9tZXIiOiJBRE1JTiIsIm1vZHVsZXMiOiJnZW5lcmFsIiwiZXhwIjozMjUwMzYxMTYwMCwiZGlhcyI6MzU3NjY5fQ.r0Z1sYcSKzDV8pkgDaVMbCYyhtin8KLm-7bG3Erjgye3yOBidq6mgpXmTE8sGWoHAKxcs9FpXZkj8U_xocsPpQ
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateAccountRequest'
              - example:
                  accountNumber: '01020501834880299'
                  product: '2001'
                  productGroup: '02'
                  branch: '501'
                  currency: VES
                  statusCuenta: A
                  statusBloqueo: P 
                  owners:
                    idType: M
                    identification: '00006937321'
                    masterGrupo: '01'
                    relationship: OWNER
            example:
              accountNumber: '01020501834880299'
              product: '2001'
              productGroup: '02'
              branch: '501'
              currency: VES
              statusCuenta: A
              statusBloqueo: P
              owners:
                idType: M
                identification: '00006937321'
                masterGrupo: '01'
                relationship: OWNER
        required: true
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response'
                - example:
                    information:
                      currentPage: -62342942
                      hasMoreData: false
                    response:
                      responseCode: Ut dolore
                      userMessage: in ipsum
              example:
                information:
                  currentPage: -62342942
                  hasMoreData: false
                response:
                  responseCode: Ut dolore
                  userMessage: in ipsum
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /addBeneficiaryOwner:
    post:
      tags:
      - BDV NOVAK
      summary: addBeneficiaryOwner
      description: 'API diseñado para agregar un beneficiario dentro de Inttegrio con los siguientes datos enviados desde un sistema externo: númerro de cuenta o contrato, sucursal, moneda y la lista de propietarios o participantes en el contrato de la cuenta que figuren tanto como propietarios o como firmantes. En este caso se asume que ambos perfiles pueden movilizar los fondos de la cuenta. En el caso de cuentas para empresas o entidades, dicha empresa o entidad debe colocarse como propietario de la cuenta y las personas naturales que movilizan la cuenta se definen como los propietarios de la misma o como sus firmantes.'
      operationId: addBeneficiaryOwner
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJlMWQ0MzMwNzI4OGM0MWZhODhlY2I2YmE1MjBmOTRjYSIsImlhdCI6MTYwMTAxMDAwMCwibmJmIjoxNTc3ODU0ODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6IkZCRU5JVEVaIiwibWFpbCI6ImZiZW5pdGV6QGludHRlZ3Jpby5jb20iLCJ1c2VyQ3VzdG9tZXIiOiJBRE1JTiIsIm1vZHVsZXMiOiJnZW5lcmFsIiwiZXhwIjozMjUwMzYxMTYwMCwiZGlhcyI6MzU3NjY5fQ.r0Z1sYcSKzDV8pkgDaVMbCYyhtin8KLm-7bG3Erjgye3yOBidq6mgpXmTE8sGWoHAKxcs9FpXZkj8U_xocsPpQ
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/addBeneficiaryOwnerRequest'
              - example:
                  businessCbsId: '10025'
                  cbsId: '10036'
            example:
              businessCbsId: '10025'
              cbsId: '10036' 
        required: true
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response'
                - example:
                    information:
                      currentPage: -62342942
                      hasMoreData: false
                    response:
                      responseCode: Ut dolore
                      userMessage: in ipsum
              example:
                information:
                  currentPage: -62342942
                  hasMoreData: false
                response:
                  responseCode: Ut dolore
                  userMessage: in ipsum
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /addOwnerAccount:
    post:
      tags:
      - BDV NOVAK
      summary: addOwnerAccount
      description: 'API diseñado para agregar un propietario de cuenta dentro de Inttegrio con los siguientes datos enviados desde un sistema externo: Número de cuenta o contrato, sucursal, moneda y la lista de propietarios o participantes en el contrato de la cuenta que figuren tanto como propietarios o como firmantes. En este caso se asume que ambos perfiles pueden movilizar los fondos de la cuenta. En el caso de cuentas para empresas o entidades, dicha empresa o entidad debe colocarse como propietario de la cuenta y las personas naturales que movilizan la cuenta se definen como los propietarios de la misma o como sus firmantes.'
      operationId: addOwnerAccount
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJlMWQ0MzMwNzI4OGM0MWZhODhlY2I2YmE1MjBmOTRjYSIsImlhdCI6MTYwMTAxMDAwMCwibmJmIjoxNTc3ODU0ODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6IkZCRU5JVEVaIiwibWFpbCI6ImZiZW5pdGV6QGludHRlZ3Jpby5jb20iLCJ1c2VyQ3VzdG9tZXIiOiJBRE1JTiIsIm1vZHVsZXMiOiJnZW5lcmFsIiwiZXhwIjozMjUwMzYxMTYwMCwiZGlhcyI6MzU3NjY5fQ.r0Z1sYcSKzDV8pkgDaVMbCYyhtin8KLm-7bG3Erjgye3yOBidq6mgpXmTE8sGWoHAKxcs9FpXZkj8U_xocsPpQ
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/addOwnerAccountRequest'
              - example:
                  accountNumber: '01020353800100028299'
                  cbsId: '10154'
            example:
              accountNumber: '01020353800100028299'
              cbsId: '10154'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response'
                - example:
                    information:
                      currentPage: -62342942
                      hasMoreData: false
                    response:
                      responseCode: Ut dolore
                      userMessage: in ipsum
              example:
                information:
                  currentPage: -62342942
                  hasMoreData: false
                response:
                  responseCode: Ut dolore
                  userMessage: in ipsum
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /addSignerAccount:
    post:
      tags:
      - BDV NOVAK
      summary: addSignerAccount
      description: 'API diseñado para crear un firmante para la cuenta dentro de Inttegrio con los siguientes datos enviados desde un sistema externo: Número de cuenta o contrato, sucursal, moneda y la lista de propietarios o participantes en el contrato de la cuenta que figuren tanto como propietarios o como firmantes. En este caso se asume que ambos perfiles pueden movilizar los fondos de la cuenta. En el caso de cuentas para empresas o entidades, dicha empresa o entidad debe colocarse como propietario de la cuenta y las personas naturales que movilizan la cuenta se definen como los propietarios de la misma o como sus firmantes.'
      operationId: addSignerAccount
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJlMWQ0MzMwNzI4OGM0MWZhODhlY2I2YmE1MjBmOTRjYSIsImlhdCI6MTYwMTAxMDAwMCwibmJmIjoxNTc3ODU0ODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6IkZCRU5JVEVaIiwibWFpbCI6ImZiZW5pdGV6QGludHRlZ3Jpby5jb20iLCJ1c2VyQ3VzdG9tZXIiOiJBRE1JTiIsIm1vZHVsZXMiOiJnZW5lcmFsIiwiZXhwIjozMjUwMzYxMTYwMCwiZGlhcyI6MzU3NjY5fQ.r0Z1sYcSKzDV8pkgDaVMbCYyhtin8KLm-7bG3Erjgye3yOBidq6mgpXmTE8sGWoHAKxcs9FpXZkj8U_xocsPpQ
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/addSignerAccountRequest'
              - example:
                  accountNumber: '411010000019'
                  cbsId: '10154'
            example:
              accountNumber: '411010000019'
              cbsId: '10154'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response'
                - example:
                    information:
                      currentPage: -62342942
                      hasMoreData: false
                    response:
                      responseCode: Ut dolore
                      userMessage: in ipsum
              example:
                information:
                  currentPage: -62342942
                  hasMoreData: false
                response:
                  responseCode: Ut dolore
                  userMessage: in ipsum
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /createBusinessBdv:
    post:
      tags:
      - BDV NOVAK
      summary: Create Business
      description: Luego de crear una o varias personas naturales, se puede enviar una petición para crear empresas o entidades como personas jurídicas.
      operationId: NewBusiness
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI3MWNlNzIxMGM4YTA0ZTE5ODVmNjkwZWZjMDk5OTJjMSIsImlhdCI6MTY4NDk3MjgwMCwibmJmIjoxNjg0OTcyODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6Ik9QQ0UyMDQiLCJtYWlsIjoianNvbGlzQHNtYXJ0LWZpbmFuY2lhbC1zeXN0ZW1zLmNvbSIsInVzZXJDdXN0b21lciI6Impkc29saXMiLCJtb2R1bGVzIjoiZ2VuZXJhbDpwZXJzb25hcyIsImV4cCI6MjI4NDQxNjAwMCwiZGlhcyI6NjkzOH0.-EYbF98N2v0hyIvLbnmeqM0uIEwHIPpWcehAcTMCjbG5TmsaTZ3p71g5fdlVjEs1nCetF5fIozAAgSeVu9rhVA
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/NewBusinessRequest'
              - example:
                  businessName: VELEZ
                  fechaConst: 2000-01-01
                  codPaisConstitucion: VE
                  id:
                    identification: '3251833'
                    type: G
                  mainAddress:
                    tipoDireccion: CAS
                    pais: VE
                    estadoP: '01'
                    codCiudad: '0100237'
                    codMunicipio: '0101'
                    codParroquia: '01'
                    codZonaPostal: '1000'
                    idZona: '3633'
                    tipoVia: AU
                    nombreVia: ALEDAÑO VIA
                    nucleo: ALDE
                    descripcionNucleo: zona Urbana
                    tipoConstruccion: '1'
                    descripcionC: '2214'
                    complemento: MZZ
                  primaryEmail: mail@mailserver.com
                  primaryPhone:
                    number: '7822456'
                    type: TEL
                    primaryTypePhone: '1'
            example:
              businessName: VELEZ
              fechaConst: 2000-01-01
              codPaisConstitucion: VE
              id:
                identification: '3251833'
                type: G
              mainAddress:
                tipoDireccion: CAS
                pais: VE
                estadoP: '01'
                codCiudad: '0100237'
                codMunicipio: '0101'
                codParroquia: '01'
                codZonaPostal: '1000'
                idZona: '3633'
                tipoVia: AU
                nombreVia: ALEDAÑO VIA
                nucleo: ALDE
                descripcionNucleo: zona Urbana
                tipoConstruccion: '1'
                descripcionC: '2214'
                complemento: MZZ
              primaryEmail: mail@mailserver.com
              primaryPhone:
                number: '7822456'
                type: TEL
                primaryTypePhone: '1'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response4'
                - example:
                    cbsId: id aliqua occaecat
                    response:
                      responseCode: laboris deserunt ex
                      userMessage: dolor
              example:
                cbsId: id aliqua occaecat
                response:
                  responseCode: laboris deserunt ex
                  userMessage: dolor
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /createIndividualBdV:
    post:
      tags:
      - BDV NOVAK
      summary: Create Individual
      description: Esta API permite crear una persona natural dentro de Inttegrio.
      operationId: CreateIndividual
      parameters:
      - name: X-Auth-Token
        in: header
        description: (Required)
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzZTEwMDQ3OGE3MjA0NWJkYjIyYTk0NTM3M2MxMGYyNyIsImlhdCI6MTY4NjcwMDgwMCwibmJmIjoxNjg2NzAwODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6Ik9QQ0UyMDQiLCJtYWlsIjoianNvbGlzQHNtYXJ0LWZpbmFuY2lhbC1zeXN0ZW1zLmNvbSIsInVzZXJDdXN0b21lciI6Ik9QQ0UyMDQiLCJtb2R1bGVzIjoicGVyc29uYXMiLCJleHAiOjIzMTgxOTg0MDAsImRpYXMiOjczMDl9.eYRMSh4xlkDR1-TwJvh8XtjFtjo0lv2iWHexz8ltg0YeFjJaEaBQAY0ikY_dnzmI2nwSjPLqfzdyjIvqgysMMw
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateIndividualRequest'
              - example:
                  cbsId: '40003287'
                  dateOfBirth: 05-18-1996
                  firstName: Antonio
                  middleName: Arelis
                  lastName: Rodriguez
                  nacionalidad: VE
                  actEconomica: A0110000
                  id:
                    identification: '929929321'
                    type: V
                  mainAddress:
                    tipoDireccion: CAS
                    pais: VE
                    estadoP: '01'
                    codCiudad: '0100237'
                    codMunicipio: '0101'
                    codParroquia: '01'
                    codZonaPostal: '1000'
                    idZona: '3633'
                    tipoVia: AU
                    nombreVia: ALEDAÑO VIA
                    nucleo: ALDE
                    descripcionNucleo: zona Urbana
                    tipoConstruccion: '5'
                    descripcionC: '2214'
                    complemento: MZZ
                  primaryPhone:
                    number: '7822456'
                    type: TEL
                    primaryTypePhone: '1'
                  gender: male
                  primaryEmail: mailto:mgrajales@smart-financial-systems.com
            example:
              cbsId: '40003287'
              dateOfBirth: 05-18-1996
              firstName: Antonio
              middleName: Arelis
              lastName: Rodriguez
              nacionalidad: VE
              actEconomica: A0110000
              id:
                identification: '929929321'
                type: V
              mainAddress:
                tipoDireccion: CAS
                pais: VE
                estadoP: '01'
                codCiudad: '0100237'
                codMunicipio: '0101'
                codParroquia: '01'
                codZonaPostal: '1000'
                idZona: '3633'
                tipoVia: AU
                nombreVia: ALEDAÑO VIA
                nucleo: ALDE
                descripcionNucleo: zona Urbana
                tipoConstruccion: '5'
                descripcionC: '2214'
                complemento: MZZ
              primaryPhone:
                number: '7822456'
                type: TEL
                primaryTypePhone: '1'
              gender: male
              primaryEmail: mailto:mgrajales@smart-financial-systems.com
        required: true 
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response4'
                - example:
                    cbsId: id aliqua occaecat
                    response:
                      responseCode: laboris deserunt ex
                      userMessage: dolor
              example:
                cbsId: id aliqua occaecat
                response:
                  responseCode: laboris deserunt ex
                  userMessage: dolor
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
  /clearCache:
    post:
      tags:
      - BDV NOVAK
      summary: Clear Cache
      description: Este API permite crear una persona natural dentro de Inttegrio.
      operationId: ClearCache
      parameters:
      - name: X-Auth-Token
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI1ZGE5MzcxYjg2MDc0Y2FkOTQyMWNlOTM1YjkxMDYxNCIsImlhdCI6MTY4MjM4MDgwMCwibmJmIjoxNjcyODc2ODAwLCJzdWIiOiI5OTAwNzY0MDAvU01BUlQgQURNSU4gVVNFUiIsImlzcyI6Ik9QQ0UyMDQiLCJtYWlsIjoiamRzb2xpc0Bob3RtYWlsLmNvbSIsInVzZXJDdXN0b21lciI6IkFETUlOIiwibW9kdWxlcyI6InBlcnNvbmFzIiwiZXhwIjozMjUwMzU5MzYwMCwiZGlhcyI6MzU2NzI3fQ.GWfwJrqiYQSsYazZQe9xBWPewsH5kPHYrf__eLwwdyS2zBD-6-F7fvRVpKxZ0lwaeA_81uX0pkw4FKkhykRFjQ
      responses:
        '200':
          description: OK
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/200response4'
                - example:
                    cbsId: id aliqua occaecat
                    response:
                      responseCode: laboris deserunt ex
                      userMessage: dolor
              example:
                cbsId: id aliqua occaecat
                response:
                  responseCode: laboris deserunt ex
                  userMessage: dolor
        '400':
          description: Bad Request
          headers:
            Inttegrio-instance:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
            MessageId:
              content:
                text/plain:
                  schema:
                    type: string
                  example: esse ad tempor
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/400response1'
                - example:
                    responseCode: aliqua dolor
                    userMessage: exercitation qui
                    action: aliquip nisi id laborum
                    messageCategory: dolor velit nisi
              example:
                responseCode: aliqua dolor
                userMessage: exercitation qui
                action: aliquip nisi id laborum
                messageCategory: dolor velit nisi
components:
  schemas:
    CreateAccountRequest:
      title: CreateAccountRequest
      required:
      - accountNumber
      - product
      - productGroup
      - branch
      - currency
      - statusCuenta
      - statusBloqueo
      - owners
      type: object
      properties:
        accountNumber:
          type: string
          description: Número de la persona
        product:
          type: string
          description: Número de producto
        productGroup:
          type: string
          description: Grupo del producto
        branch:
          type: string
          description: Sucursal del usuario
        currency:
          type: string
          description: Moneda
        statusCuenta:
          type: string
          description: Estado de la cuenta, los valores aceptados son A, C, R, P.
        statusBloqueo:
          type: string
          description: Estado del bloqueo.
        owners:
          type: array
          items:
            $ref: '#/components/schemas/Owner'
          description: Array de objetos tipo Owner
      example:
        accountNumber: '01020501834880299'
        product: '2001'
        productGroup: '02'
        branch: '501'
        currency: VES
        statusCuenta: A
        statusBloqueo: P
        owners:
          idType: M
          identification: '00006937321'
          masterGrupo: '01'
          relationship: OWNER
    Owner:
      title: Owner
      required:
      - idType
      - identification
      - masterGrupo
      - relationship
      type: object
      properties:
        idType:
          type: string
          description: Tipo de identificación
        identification:
          type: string
          description: Identificación
        masterGrupo: 
          type: string
          description: Grupo maestro 
        relationship:
          type: string
          description: La relación
      example:
        idType: M
        identification: '00006937321'
        masterGrupo: '01'
        relationship: OWNER
    200response:
      title: 200response
      required:
      - information
      - response
      type: object
      properties:
        information:
          $ref: '#/components/schemas/Information'
        response:
          $ref: '#/components/schemas/Response'
      example:
        information:
          currentPage: -62342942
          hasMoreData: false
        response:
          responseCode: Ut dolore
          userMessage: in ipsum
    Information:
      title: Information
      required:
      - currentPage
      - hasMoreData
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        hasMoreData:
          type: boolean
      example:
        currentPage: -62342942
        hasMoreData: false
    Response:
      title: Response
      required:
      - responseCode
      - userMessage
      type: object
      properties:
        responseCode:
          type: string
        userMessage:
          type: string
      example:
        responseCode: Ut dolore
        userMessage: in ipsum
    201response:
      title: 201response
      required:
      - information
      - response
      type: object
      properties:
        information:
          $ref: '#/components/schemas/Information'
        response:
          $ref: '#/components/schemas/Response'
      example:
        information:
          currentPage: -62342942
          hasMoreData: false
        response:
          responseCode: Ut dolore
          userMessage: in ipsum
    400response1:
      title: 400response1
      required:
      - responseCode
      - userMessage
      - action
      - messageCategory
      type: object
      properties:
        responseCode:
          type: string
        userMessage:
          type: string
        action:
          type: string
        messageCategory:
          type: string
      example:
        responseCode: aliqua dolor
        userMessage: exercitation qui
        action: aliquip nisi id laborum
        messageCategory: dolor velit nisi
    401response1:
      title: 401response1
      required:
      - responseCode
      - userMessage
      - action
      - messageCategory
      type: object
      properties:
        responseCode:
          type: string
        userMessage:
          type: string
        action:
          type: string
        messageCategory:
          type: string
      example:
        responseCode: aliqua dolor
        userMessage: exercitation qui
        action: aliquip nisi id laborum
        messageCategory: dolor velit nisi
    addBeneficiaryOwnerRequest:
      title: addBeneficiaryOwnerRequest
      required:
      - businessCbsId
      - cbsId
      type: object
      properties:
        businessCbsId:
          type: string
          description: Cpersona de la persona jurídica
        cbsId:
          type: string
          description: Cpersona del beneficiario
      example:
        businessCbsId: '10025'
        cbsId: '10036'
    addOwnerAccountRequest:
      title: addOwnerAccountRequest
      required:
      - accountNumber
      - cbsId
      type: object
      properties:
        accountNumber:
          type: string
          description: Cuenta de la persona
        cbsId:
          type: string
          description: Cpersona del cotitular
      example:
        accountNumber: '01020353800100028299'
        cbsId: '10154'
    addSignerAccountRequest:
      title: addSignerAccountRequest
      required:
      - accountNumber
      - cbsId
      type: object
      properties:
        accountNumber:
          type: string
          description: Número de cuenta
        cbsId:
          type: string
          description: Cpersona del firmante
      example:
        accountNumber: '411010000019'
        cbsId: '10154'
    NewBusinessRequest:
      title: NewBusinessRequest
      required:
      - businessName
      - fechaConst
      #- actEconomica
      - codPaisConstitucion
      #- sector
      - id
      - mainAddress
      - primaryEmail
      - primaryPhone
      type: object
      properties:
        businessName:
          type: string
          description: Nombre de la empresa
        fechaConst:
          type: string
          description: Fecha de constitución
        #actEconomica:
          #type: string
          #description: Actividad económica de la empresa
        codPaisConstitucion:
          type: string
          description: Código de país constitución
        #sector:
          #type: string
          #description: Sector económico
        id:
          $ref: '#/components/schemas/Id'
        mainAddress:
          $ref: '#/components/schemas/MainAddress'
        primaryEmail:
          type: string
          description: Correo principal
        primaryPhone:
          $ref: '#/components/schemas/PrimaryPhone'
          description: Teléfono Principal
      example:
        businessName: VELEZ
        fechaConst: 2000-01-01
        #actEconomica: A0100000
        codPaisConstitucion: VE
        #sector: '110'
        id:
          identification: '3251833'
          type: G
        mainAddress:
          tipoDireccion: CAS
          pais: VE
          estadoP: '01'
          codCiudad: '0100237'
          codMunicipio: '0101'
          codParroquia: '01'
          codZonaPostal: '1000'
          idZona: '3633'
          tipoVia: AU
          nombreVia: ALEDAÑO VIA
          nucleo: ALDE
          descripcionNucleo: zona Urbana
          tipoConstruccion: '1'
          descripcionC: '2214'
          complemento: MZZ
        primaryEmail: mail@mailserver.com
        primaryPhone:
          number: '7822456'
          type: TEL
          primaryTypePhone: '1'
    Id:
      title: Id
      required:
      - identification
      - type
      type: object
      properties:
        identification:
          type: string
          description: Se ingresa el número de identificación
        type:
          type: string
          description: Se ingresa el tipo de identificación
      example:
        identification: '3251833'
        type: G
    MainAddress:
      title: MainAddress
      required:
      - tipoDireccion
      - pais
      - estadoP
      - codCiudad
      - codMunicipio
      - codParroquia
      - codZonaPostal
      - idZona
      - tipoVia
      - nombreVia
      - nucleo
      - descripcionNucleo
      - tipoConstruccion
      - descripcionC
      - complemento
      type: object
      properties:
        tipoDireccion:
          type: string
          description: Se ingresa el tipo de dirección (String - 3)
        pais:
          type: string
          description: Se ingresa el código del país de residencia ( String - 3)
        estadoP:
          type: string
          description: Se ingresa el código del estado (String - 10)
        codCiudad:
          type: string
          description: Se ingresa el código de la ciudad (String - 7)
        codMunicipio:
          type: string
          description: Se ingresa el código del municipio (String - 50)
        codParroquia:
          type: string
          description: Se ingresa el código de la parroquia (String - 20)
        codZonaPostal:
          type: string
          description: Se ingresa el código de la zona postal (String - 15)
        idZona:
          type: string
          description: Se ingresa el id de la zona postal (String -15)
        tipoVia:
          type: string
          description: Se ingresa el código de tipo de la Vía (String - 43)
        nombreVia:
          type: string
          description: Se ingresa el nombre de la vía (String - 100)
        nucleo:
          type: string
          description: Se ingresa el nombre abreviado del núcleo (String - 4)
        descripcionNucleo:
          type: string
          description: Se ingresa la descripción del núcleo
        tipoConstruccion:
          type: string
          description: Se ingresa el tipo de inmueble (String - 20)
        descripcionC:
          type: string
          description: Se ingresa el numero de la trasversal (String - 40 )
        complemento:
          type: string
          description: Se ingresa el complemento de la trasversal (String - 10)
      example:
        tipoDireccion: CAS
        pais: VE
        estadoP: '01'
        codCiudad: '0100237'
        codMunicipio: '0101'
        codParroquia: '01'
        codZonaPostal: '1000'
        idZona: '3633'
        tipoVia: AU
        nombreVia: ALEDAÑO VIA
        nucleo: ALDE
        descripcionNucleo: zona Urbana
        tipoConstruccion: '1'
        descripcionC: '2214'
        complemento: MZZ
    PrimaryPhone:
      title: PrimaryPhone
      required:
      - number
      - type
      - primaryTypePhone
      type: object
      properties:
        number:
          type: string
          description: Se ingresa el numero de teléfono o celular (String - 12)
        type:
          type: string
          description: Se ingresa el tipo de teléfono (String - 3)
        primaryTypePhone:
          type: string
          description: Se ingresa 1 si es el teléfono principal de la persona (String - 1)
      example:
        number: '7822456'
        type: TEL
        primaryTypePhone: '1'
    SecondaryPhone:
      title: SecondaryPhone
      required:
      - number
      - type
      type: object
      properties:
        number:
          type: string
          description: Se ingresa el número de teléfono
        type:
          type: string
          description: Se ingresa el tipo de teléfono
      example:
        number: '7876643'
        type: CEL
    BeneficiaryOwner:
      title: BeneficiaryOwner
      required:
      - cbsId
      - percentage
      type: object
      properties:
        cbsId:
          type: string
        percentage:
          type: integer
          format: int32
      example:
        cbsId: '8493'
        percentage: 25
    200response4:
      title: 200response4
      required:
      - cbsId
      - response
      type: object
      properties:
        cbsId:
          type: string
        response:
          $ref: '#/components/schemas/Response'
      example:
        cbsId: id aliqua occaecat
        response:
          responseCode: laboris deserunt ex
          userMessage: dolor
    201response4:
      title: 201response4
      required:
      - cbsId
      - response
      type: object
      properties:
        cbsId:
          type: string
        response:
          $ref: '#/components/schemas/Response'
      example:
        cbsId: id aliqua occaecat
        response:
          responseCode: laboris deserunt ex
          userMessage: dolor
    NewBusinessCopyRequest:
      title: NewBusinessCopyRequest
      required:
      - businessName
      - id
      - mainAddress
      - primaryEmail
      - primaryPhone
      type: object
      properties:
        businessName:
          type: string
        id:
          $ref: '#/components/schemas/Id1'
        mainAddress:
          $ref: '#/components/schemas/MainAddress'
        primaryEmail:
          type: string
        primaryPhone:
          $ref: '#/components/schemas/PrimaryPhone'
      example:
        businessName: VELEZ
        id:
          identification: '00007733137'
          type: J
          fechaConst: 2000-01-01
          actEconomica: A0100000
          codPaisConstitucion: VE
        mainAddress:
          tipoDireccion: CAS
          pais: VE
          estadoP: '01'
          codCiudad: '0100237'
          codMunicipio: '0101'
          codParroquia: '01'
          codZonaPostal: '1000'
          idZona: '3633'
          tipoVia: AU
          nombreVia: ALEDAÑO VIA
          nucleo: ALDE
          descripcionNucleo: zona Urbana
          tipoConstruccion: '1'
          descripcionC: '2214'
          complemento: MZZ
        primaryEmail: mail@mailserver.com
        primaryPhone:
          number: '7822456'
          type: TEL
          primaryTypePhone: '1'
    Id1:
      title: Id1
      required:
      - identification
      - type
      - fechaConst
      - codPaisConstitucion
      type: object
      properties:
        identification:
          type: string
        type:
          type: string
        fechaConst:
          type: string
        #actEconomica:
          #type: string
        codPaisConstitucion:
          type: string
      example:
        identification: '00007733137'
        type: J
        fechaConst: 2000-01-01
        #actEconomica: A0100000
        codPaisConstitucion: VE
    CreateIndividualRequest:
      title: CreateIndividualRequest
      required:
      - cbsId
      - dateOfBirth
      - firstName
      - middleName
      - lastName
      - nacionalidad
      - actEconomica
      - ids
      - mainAddress
      - primaryPhone
      - gender
      - primaryEmail
      type: object
      properties:
        cbsId:  
          type: string
          description: Cpersona de la persona
        dateOfBirth:
          type: string
          description: Se ingresa la fecha de nacimiento de de la persona natural en tipo (Date)
        firstName:
          type: string
          description: Se ingresa el primer nombre de la personas tipo (String-40)
        middleName:
          type: string
          description: Se ingresa el segundo nombre de la personas tipo (String- 30)
        lastName:
          type: string
          description: Se ingresa el primer apellido de la persona tipo (String - 25)
        nacionalidad:
          type: string
          description: Se ingresa el país de nacimiento (String- 3)
        actEconomica:
          type: string
          description: Se ingresa el código de actividad económica (String - 10)
        id:
          $ref: '#/components/schemas/Id'
        mainAddress:
          $ref: '#/components/schemas/MainAddress'
        primaryPhone:
          $ref: '#/components/schemas/PrimaryPhone'
        gender:
          type: string
          description: El género de la persona en minúscula. Solo se aceptan los valores "male" y "female".  
        primaryEmail:
          type: string
          description: Correo principal
      example:
        cbsId: '40003287'
        dateOfBirth: 05-18-1996
        firstName: Antonio
        middleName: Arelis
        lastName: Rodriguez
        nacionalidad: VE
        actEconomica: A0110000
        id:
          identification: '929929321'
          type: V
        mainAddress:
          tipoDireccion: CAS
          pais: VE
          estadoP: '01'
          codCiudad: '0100237'
          codMunicipio: '0101'
          codParroquia: '01'
          codZonaPostal: '1000'
          idZona: '3633'
          tipoVia: AU
          nombreVia: ALEDAÑO VIA
          nucleo: ALDE
          descripcionNucleo: zona Urbana
          tipoConstruccion: '5'
          descripcionC: '2214'
          complemento: MZZ
        primaryPhone:
          number: '7822456'
          type: TEL
          primaryTypePhone: '1'
        gender: male
        primaryEmail: mailto:mgrajales@smart-financial-systems.com
tags:
- name: BDV NOVAK
  description: ''